# Generated by Django 3.0.5 on 2020-05-08 15:32

from django.db import migrations

def load_initial_data(apps, schema_editor):
    # get the correct versions of models using the app registry
    Category = apps.get_model("recommendations", "Category")

    allowed_states = ['a', 'b', 'c']
    res = []
    for state in allowed_states:
        cat = Category(abbreviation=state, description='Dunno')
        res.append(cat)
    Category.objects.bulk_create(res)

def do_it_again(apps, s):
    Question = apps.get_model('recommendations', 'Question')
    Category = apps.get_model("recommendations", "Category")
    res2 = []
    for cat in Category.objects.all():
        res2.append(Question(category=cat, text='is it {}'.format(cat.description)))
    Question.objects.bulk_create(res2)


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
        migrations.RunPython(do_it_again)
    ]
