# Generated by Django 3.0.5 on 2020-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20200508_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.IntegerField(choices=[('1', 'Just Started'), ('2', 'Quiz'), ('3', 'Finished')], default='1'),
        ),
    ]
