# Generated by Django 3.0.5 on 2020-05-10 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20200508_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='url1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.IntegerField(choices=[('0', 'Start'), ('1', 'Quiz'), ('2', 'Prediction'), ('3', 'Finish')], default='0'),
        ),
        migrations.CreateModel(
            name='SessionRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Session')),
            ],
        ),
    ]
