# Generated by Django 3.0.5 on 2020-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20200510_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='url2',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
